[global]
keyboard = "en"
country = "us"
fqdn = "pve01.longsnet.com"
mailto = "ethan.j.long@gmail.com"
timezone = "America/Denver"
root-password = "12345678"
root-ssh-keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINrqJvg04jFyiX1X81rA+ff7DFM+9wYWbonud2F+E1O+ fedora"
]

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "zfs"
zfs.raid = "raid0"
filter.ID_SERIAL = "SAMSUNG*"
